### ISSUE TITLE
I thought XCP 1.6.3 is out

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/xcp#14]
Page: [Get started with XCP](https://docs.netapp.com/us-en/xcp/index.html)

The What's New section still references 1.6.2.

Thanks for all y'all do.

**Comment by netapp-pcarriga** [comment]
Hi John, thank you for catching this. I'll get this updated as soon as possible.

**Comment by netapp-pcarriga** [comment]
The What's New section was legacy content from XCP 1.6.2. 

This issue is now fixed.

Thank you again for bringing this to our attention.
