### ISSUE TITLE
SMB Support for -exclude

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/xcp#17]
Page: [Filters](https://docs.netapp.com/us-en/xcp/xcp-filters.html)

Hi,
 I thought the 1.6.3 release of NetApp XCP now also has support for SMB.
 
 Thanks!

**Comment by netapp-pcarriga** [comment]
Hi John,

thank you for enquiry. I'll look into this and get back to you as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi John,

I can confirm that SMB support for the -exclude command option is available in the XCP v1.6.3 release.

You can access the information in the XCP v1.6.3 Reference document available on the NetApp Support Site using this link https://library.netapp.com/ecm/ecm_download_file/ECMLP2875795

Go to the "scan-exclude" information for SMB command references on pages 72 and 73.
