### ISSUE TITLE
-exclude with xcp avaialble 

### ISSUE THREAD

**Issue by blassen** [NetAppDocs/xcp#18]
Page: [Filters](https://docs.netapp.com/us-en/xcp/xcp-filters.html)

As of 1.6.3 the -exclude modifier is also available in the SMB version of xcp

**Comment by netapp-pcarriga** [comment]
Hi Lassen,
Thank you for your feedback. 
I'll look into this and get back to you as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi Lassen,

the change has been implemented to include the "exclude" filter option for SMB.
