### ISSUE TITLE
Update request (System Requreiments)

### ISSUE THREAD

**Issue by fujita2** [NetAppDocs/xcp#21]
Page: [Install XCP NFS](https://docs.netapp.com/us-en/xcp/xcp-install-xcp-nfs.html)

The description of System Requreiments is written in one table with xcp and file analytics.
Could you split this one table into two tables?
Or is xcp no longer supported to work on RHEL6 and 7?

**Comment by netapp-pcarriga** [comment]
Thank you, we'll respond to your enquiry as soon as possible.

**Comment by netapp-pcarriga** [comment]
I can confirm that XCP is supported for RHEL8 only, this information is available from the NetApp [IMT](https://mysupport.netapp.com/matrix/).
