### ISSUE TITLE
Page displays "Error! Reference source not found." rather than appropriate file path

### ISSUE THREAD

**Issue by tespinoz-ntap** [NetAppDocs/xcp#29]
Page: [](https://docs.netapp.com/us-en/xcp/xcp-logging-for-nfs-and-smb.html)

The page for XCP logging displays "Error! Reference source not found." in both the "Config JSON file location" table and step 4 of the "Configure the JSON configuration file" section. I'm not sure what the appropriate values should be, but it appears to be referencing a location that may not exist.

**Comment by netapp-aoife** [comment]
Hi, thanks very much for bringing this to our attention. We'll investigate this and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
We have now updated the documentation to address this issue: https://docs.netapp.com/us-en/xcp/xcp-logging-for-nfs-and-smb.html

Thanks again for raising this issue.
