### ISSUE TITLE
ACLs and Mode bits

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/xcp#34]
Page: [Unsupported features](https://docs.netapp.com/us-en/xcp/xcp-unsupported-features.html)

Can we please clarify this statement
ACLs | When the source is a non-NetApp system, XCP does not copy ACLs.

Mode bits (typically used with NFS v3) are copied as expected.

**Comment by netapp-pcarriga** [comment]
@louvipi - HI John, thanks for your request. We'll add clarification and update you here when it's published.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [Unsupported features](https://docs.netapp.com/us-en/xcp/xcp-unsupported-features.html)
