### ISSUE TITLE
Update link to reference page

### ISSUE THREAD

**Issue by SuperJT** [NetAppDocs/xcp#44]
### Summary

In the Index page,
https://github.com/NetAppDocs/xcp/blob/main/index.adoc, we point to xcp.netapp.com to get the reference documentation.
On xcp.netapp.com, we point to https://github.com/NetAppDocs/xcp/blob/main/index.adoc, to get the reference documentation.  
Can we update the link in the index.adoc to point to https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=63064

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @SuperJT thanks for bringing this to our attention. We'll verify and update the documentation.

**Comment by netapp-aoife** [comment]
Hi @SuperJT  thanks again for your suggestion. This change has now been made to the documentation here: https://docs.netapp.com/us-en/xcp/index.html
