### ISSUE TITLE
In SMB, it is not possible to count the size "Used" by user.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/xcp#50]
### Page URL

https://docs.netapp.com/us-en/xcp/xcp-run-a-scan.html

### Page title

Run a scan

### Summary

![image](https://github.com/NetAppDocs/xcp/assets/68621663/4ca1229f-3804-4b10-8b94-896257957948)

There is a missing note that only NFS is supported.
The Users Guide for XCP v1.6.1 includes the table below, but the ability to count capacity by user is not supported in SMB.

![image](https://github.com/NetAppDocs/xcp/assets/68621663/09f7b7de-2267-4417-b3a0-741c1ed44b9a)

The release notes below also do not mention that the feature have been added in XCP v1.6.2 or later versions.
https://library.netapp.com/ecm/ecm_download_file/ECMLP2886695

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @kanitani, thank you for bringing this to our attention. We will verify with the XCP team and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Thank you for contacting us. This topic refers to an earlier product release and has been archived; we are not planning further updates. For the latest documentation on this product, see https://docs.netapp.com/us-en/xcp/index.html

**Comment by kanitani** [comment]
Is it currently possible to count "the amount of space used by a user" in SMB?
If not, please add a note here (stating that it is not possible in SMB).
If it is possible, please state from which version it became possible.

**Comment by netapp-aoife** [comment]
Thanks @kanitani for providing further feedback. We'll investigate and will send you an update soon.

**Comment by netapp-aoife** [comment]
Hi @kanitani Our documentation supports the latest version of the XCP tool, as well as the three most recent versions. I have confirmed that it is currently possible to count "the amount of space used by a user" in SMB and NFS for XCP 1.9.1 and later so we will not be making a doc update at this time. However, if you have a question about a specific version older than XCP 1.9.1, please let me know and I will check with XCP engineering about support for that specific version.

**Comment by netapp-aoife** [comment]
Closing this issue as there is no documentation update required.
