### ISSUE TITLE
XCP SMB, xcp.ini not required

### ISSUE THREAD

**Issue by st4cy001** [NetAppDocs/xcp#59]
### Page URL

https://docs.netapp.com/us-en/xcp/xcp-prepare-windows-for-xcp-smb.html

### Page title

Prepare Windows for XCP SMB

### Summary

XCP SMB, xcp.ini not required

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @st4cy001 thanks for bringing this to our attention. We'll verify and let you know when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @st4cy001 thanks again for raising this issue. We've updated the documentation here to address your feedback: https://docs.netapp.com/us-en/xcp/xcp-configure-the-ini-file-for-xcp-nfs.html
